### ISSUE TITLE
Added to registry themes

### ISSUE THREAD

**Issue by thomasdavis** [davcd/jsonresume-theme-actual#12]
You really nailed this theme, I wish I added it earlier.

https://registry.jsonresume.org/thomasdavis?theme=actual

The PDF support is off the charts, what's the magic trick?!?!

**Comment by davcd** [comment]
Hello @thomasdavis many thanks for your words!
I'm planning to provide full support of the v1.0.0 schema in the next version of the theme.
For the PDF export I just did some CSS! For me, the puppeteer library worked as expected.
