### ISSUE TITLE
Name of the generated HTML page is 'Actual theme for JSON Resume'

### ISSUE THREAD

**Issue by wjam** [davcd/jsonresume-theme-actual#16]
I'm poking around with jsonresume and associated themes and noticed that the title of the HTML page is 'Actual theme for JSON Resume' rather than something meaningful like `resume.basics.name`.

**Comment by davcd** [comment]
Hello @wjam many thanks for your comments, I'm agree with this and I going to change it in the next release of the theme.

**Comment by maartenpaauw** [comment]
I've create a pull request which will use the name and the label as title. For example: "Richard Hendrik - Software Developer".
